services:

  backend:
    build: ./backend
    container_name: shop-backend
    expose:
      - "3000"

  frontend:
    build: ./frontend
    container_name: shop-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend